### ISSUE TITLE
No insightful error message when field data not implemented as a property 

### ISSUE THREAD

**Issue by ERKuipers** [computationalgeography/campo#4]
Error messages are not insightful or are missing when adding / adjusting a field property fails. For spatially explicit data, the data needs to be assigned along a specific axis so as to represent it potentially being an internally varying agent (error: cannot write to dataset), but this is not clear from the error. In the dynamic model, no error messages are given when the field property is not implemented.

**Comment by OliverSchmitz** [comment]
Error checking and improved messages were added
